---
title: "Github-pages-with-jekyll"
date: 2022-03-21
---
title: Customize Github page
author: Akhil George
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Training for git under EN-862 in thinkific.
Currently, on customize github page with jekyll.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
